version: '3'

services:
  dac-portal:
    build:
      context: ./DAC-Portal
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - "./DAC-Portal/src:/app/src"
      - "./DAC-Portal/public:/app/public"
      - "./DAC-Portal/server:/app/server"
    links:
      - keycloak
      - postgres
      - mongo
    networks:
      dac-network:
        ipv4_address: 172.21.0.14
  postgres:
      image: postgres
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      networks:
        dac-network:
          ipv4_address: 172.21.0.13
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        DB_VENDOR: ${DB_VENDOR}
        DB_ADDR: ${DB_ADDR}
        DB_DATABASE: ${DB_DATABASE}
        DB_USER: ${DB_USER}
        DB_SCHEMA: ${DB_SCHEMA}
        DB_PASSWORD: ${DB_PASSWORD}
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        #KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
      volumes:
        - "./keycloak/realms:/opt/jboss/keycloak/imports"
      command:
        - '-b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.migration.strategy=IGNORE_EXISTING'
      ports:
        - 8080:8080
      links:
        - postgres
      networks:
        dac-network:
          ipv4_address: 172.21.0.12
  permissions-api:
    build:
      context: ./Permissions-API
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    env_file:
      - .env-permissions
    links:
      - mongo
      - keycloak
    volumes:
      - "./Permissions-API/src:/app/src"
    networks:
      dac-network:
        ipv4_address: 172.21.0.11
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - 27017:27017
    links:
      - keycloak
    volumes:
      - ./mongodb-example:/data/db
    networks:
      dac-network:
        ipv4_address: 172.21.0.10
networks:
  dac-network:
    ipam:
      config:
        - subnet: 172.21.0.0/24
